apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName.model }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.appName.model }}
    template:
        metadata:
            labels:
                app: {{ .Values.appName.model }}
        spec:
            containers:
                - name: {{ .Values.appName.model }}
                  image: {{ .Values.image.modelServer }}
                  resources:
                    limits:
                      memory: "1Gi"
                      cpu: "1000m"
                  ports:
                      - containerPort: 8000
                  env:
                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: hostname
                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: port
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretKey.redis }}
                                key: db_password
                      - name: "MODEL_NAME"
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.modelServer }}
                                key: gpt_model