apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName.model }}
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: {{ .Values.appName.model }}
    ports:
        - port: 8000
          targetPort: 8000
    