apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configMap.modelServer }}
    namespace: {{ .Values.namespace }}
data:
    model_server_url: "http://{{ .Values.appName.model }}:8000"
    gpt_model: {{ .Values.model }}  