apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName.web }}
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: {{ .Values.appName.web }} 
    ports:
        - port: 9000
          targetPort: 9000