apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName.web }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.appName.web }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.appName.web }}
    template:
        metadata:
            labels:
                app: {{ .Values.appName.web }}
        spec:
            containers:
                - name: {{ .Values.appName.web }}
                  image: {{ .Values.image.webServer }}
                  resources:
                      limits:
                          memory: "500Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
                  env:
                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: hostname
                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: port
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretKey.redis }}
                                key: db_password
                      - name: MODEL_SERVER_URL
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.modelServer }}
                                key: model_server_url
